### ISSUE TITLE
No cmake option to build shared library

### ISSUE THREAD

**Issue by antoscha** [electronic-structure/SIRIUS#288]
Dear Developers,
It would be great if you added a feature to build SIRIUS with cmake as a shared library.
Thank you in advance.

**Comment by simonpintarelli** [comment]
Hello,

thank you for your request!
The cmake in branch `build_shared_library`, [link](https://github.com/electronic-structure/SIRIUS/tree/build-shared-library), builds both static and shared (libsirius.so) libraries by default. Note that there is only a library if either CUDA or Fortran bindings are activated, otherwise SIRIUS is header only. E.g. to build the shared library containing the CUDA kernels and the Fortran bindings use the following flags for cmake (default for both CUDA/Fortran is Off)
```
cmake -DCREATE_FORTRAN_BINDINGS=On -DUSE_CUDA=On -DCMAKE_INSTALL_PREFIX=/install/path /path/to/SIRIUS
```

We will remove the branch as soon we merge it into develop or master.

**Comment by antoscha** [comment]
Thank you!
